# Generated by Django 4.0.2 on 2022-02-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriving_date', models.DateTimeField(auto_now_add=True)),
                ('check_out_date', models.DateTimeField(auto_now=True)),
                ('adults', models.IntegerField(default=1)),
                ('childs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('CS', 'CASH'), ('CR', 'CARD'), ('MT', 'MONEY TRANSFER')], default='CS', max_length=15)),
                ('car_plates', models.CharField(max_length=15)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hasDebt', models.BooleanField(default=False)),
                ('vehicle', models.CharField(max_length=30)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.guest_booking')),
            ],
        ),
    ]
